[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Resource identifiers for Matrix."
documentation = "https://docs.rs/ruma-identifiers"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.11.0"

[dependencies]
lazy_static = "0.2"
rand = "0.3"
regex = "0.2"
serde = "1.0"
url = "1.4"

[dependencies.diesel]
optional = true
version = "1.3"

[dev-dependencies]
serde_json = "1.0"
